version: '{build}'

environment:
  matrix:
    # for Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    # only enable one version, otherwise it takes too long!
    - PYTHON: "C:\\Python38-x64"

image: Visual Studio 2019

install:
  - git submodule update --recursive --init
  # we need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
